SIMPLE_TOP.v
SAFETY/SIMPLE_TOP_PARITY.v

//${BOS_LIB_HOME}/RTL/SAFETY/DCLS_COMPARATOR_TEMPLATE.v
//${BOS_LIB_HOME}/bos_logic/CLK_RST_LVT/BOS_SOC_RSTSYNCH.v
//${BOS_LIB_HOME}/RTL/BOS_ERROR_DOUBLE.v
//${BOS_LIB_HOME}/bos_logic/RVT/BOS_SOC_DFFS.v
//${BOS_LIB_HOME}/bos_logic/LVT/BOS_SOC_SYNCHSR_LVT.v
//${BOS_LIB_HOME}/bos_logic/LVT/BOS_SOC_GFMUX_LVT.v
//${BOS_LIB_HOME}/bos_logic/RVT/BOS_SOC_SYNCHSR.v
//${BOS_LIB_HOME}/bos_logic/RVT/BOS_SOC_DFFR.v