#!/bin/tcsh

\rm *.log
\rm *.lck
\rm -rf *_svf
\rm -rf reports
\rm -rf vcst_rtdb 

\rm -rf FM_INFO*
\rm -rf FM_WORK*
\rm -rf csrc
\rm -rf simv.daidir
\rm -rf sim.fsdb*
\rm verdi_config_file
\rm -rf verdiLog
\rm ucli.key
\rm novas.*
\rm simv

